// components/ThemeToggle.tsx
import { useTheme } from "next-themes"
import { useEffect, useState } from 'react'


export default function ThemeToggle({className = ""}) {
    const [mounted, setMounted] = useState(false)
    const { systemTheme, theme, setTheme } = useTheme();

    useEffect(() => setMounted(true), [])
    if (!mounted) return null

    const renderThemeIcon = () => {
        const currTheme = theme === 'system' ? systemTheme : theme

        if(currTheme === "dark"){
            return (
                <svg // bulb icon
                className="h-7 w-7 hover:scale-110 cursor-pointer"
                onClick={() => { setTheme("light") }}
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                >
                    <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                    />
                </svg>
            )
        } else {
            return (
                <svg  // moon icon
                className="h-7 w-7 hover:scale-110 cursor-pointer"
                onClick={() => { setTheme("dark") }}
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
                />
                </svg>
            )
        }
    }

    return (
        <div className={className}>
            { renderThemeIcon() }
        </div>
    )
}

// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { onMount } from "svelte"

  let dark: boolean

  onMount(() => {
    dark = document.documentElement.classList.contains("dark")
  })

  const toogleTheme = () => {
    document.documentElement.classList.toggle("dark")
    dark = !dark
    localStorage.theme = dark ? "dark" : "light"
  }
</script>

<svelte:head>
  <script>
    // Set based on preference in head tag to avoid FOUC
    if (
      localStorage.theme === "dark" ||
      (!localStorage.theme && window.matchMedia("(prefers-color-scheme: dark)").matches)
    ) {
      document.documentElement.classList.add("dark")
    } else {
      document.documentElement.classList.remove("dark")
    }
  </script>
</svelte:head>

<button on:click={toogleTheme} class="absolute top-4 right-4">
  {#if dark}
    <svg
      class="icon hover:scale-110 text-zinc-100"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width={1.5}
        d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
      />
    </svg>
  {:else}
    <svg
      class="icon hover:scale-110 text-zinc-900"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width={1.5}
        d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
      />
    </svg>
  {/if}
</button>

<style>
  .icon {
    height: 2.25rem;
    width: 2.25rem;
    cursor: pointer;
  }
</style>
